version:	"3.5"
services:
  app:
    build: .
    environment:
      TERM: "xterm"
      DEV: true
    ports:
      - "8080:80"
    container_name: "quizapp"
    volumes:
      - ..:/home/app

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: quiz
    ports:
      - "3000:3306"
    container_name: "quizdb"
