version: "3.5"
services:
  app:
    build: .
    environment:
      - TERM=xterm
    ports:
      - "8080:80"
      - "2222:22"
    container_name: "project"
    volumes:
      - ..:/home/project
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: projectdb
    ports:
      - "3000:3306"
