version: "3.5"
services:
  app:
    build: .
    environment:
      - TERM=xterm
    ports:
      - "8080:80"
      - "2222:22"
    container_name: "project"
    volumes:
      - ..:/home/project
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3000:3306"
